# Generated by Django 6.0 on 2026-01-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='questions',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
