# Generated by Django 6.0 on 2026-01-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_questions_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='quizzes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Quizzes',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
