# Generated by Django 6.0 on 2026-01-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_questions_choice_quizzes_questions_quiz_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='tags',
        ),
        migrations.AddField(
            model_name='quizzes',
            name='tags',
            field=models.ManyToManyField(related_name='quizzes', to='app.tags'),
        ),
    ]
