# Generated by Django 6.0 on 2026-01-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_quizzes_tags_quizzes_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='quizzes',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Quizzes',
        ),
    ]
