# Generated by Django 6.0 on 2026-01-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_quizzes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='quiz_questions',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Quizzes',
        ),
    ]
