# Generated by Django 6.0 on 2026-01-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_questions_choice_quizzes_questions_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='quiz_questions',
        ),
    ]
